// Default addresses — overwritten by deploy script output
let addresses = {
  nftCollection: "0x5FbDB2315678afecb367f032d93F642f64180aa3",
  marketplace: "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512",
  oracle: "0x0000000000000000000000000000000000000000",
};

// Try to load deployed addresses (generated by deploy script)
try {
  const deployed = await import("./deployed-addresses.json");
  addresses = { ...addresses, ...deployed.default };
} catch {
  // Use defaults (first two Hardhat deploy addresses)
}

export const NFT_COLLECTION_ADDRESS = addresses.nftCollection;
export const MARKETPLACE_ADDRESS = addresses.marketplace;
export const ORACLE_ADDRESS = addresses.oracle;

// ABIs — will be populated after first deploy, fallback to inline
export { default as NFTCollectionABI } from "./abis/NFTCollection.json";
export { default as NFTMarketplaceABI } from "./abis/NFTMarketplace.json";
